/** 51-state contractor legal database — licensing, lien law, prevailing wage, OSHA */

export interface StateLegalData {
  licensing: string;
  bond: string;
  lienLaw: string;
  workerClassification: string;
  prevailingWage: string;
  osha: string;
  continuingEducation: string;
}

export const STATE_LEGAL: Record<string, StateLegalData> = {
  Virginia: {
    licensing: 'Class A (>$120K), B ($10K–$120K), or C (<$10K) contractor license from DPOR.',
    bond: 'Class A: no bond required. Class B/C: varies by classification.',
    lienLaw: 'Mechanics lien must be filed within 90 days of last work. Preliminary notice required for residential >$1,000 within 30 days of first furnishing.',
    workerClassification: 'Virginia follows IRS 20-factor test for worker classification. ABC test not adopted.',
    prevailingWage: 'Virginia Overtime Wage Act — public projects over $500K require prevailing wages (effective 2022). Davis-Bacon applies to federal projects.',
    osha: 'Virginia has a state OSHA plan (VOSH). Separate standards may apply for certain industries.',
    continuingEducation: 'No mandatory CE for general contractors. Some specialty trades have requirements.',
  },
  Georgia: {
    licensing: 'No state general contractor license required. Some counties/cities require local licenses. Utility contractors need state license.',
    bond: 'Varies by local jurisdiction.',
    lienLaw: 'Mechanics lien filed within 90 days of substantial completion. Subcontractors must file notice within 30 days of starting work.',
    workerClassification: 'Georgia follows federal IRS guidelines for worker classification.',
    prevailingWage: 'No state prevailing wage law.',
    osha: 'Federal OSHA applies — no state plan.',
    continuingEducation: 'N/A — no state contractor license.',
  },
  Minnesota: {
    licensing: 'Residential contractor license required. Commercial/industrial: no state license but local permits required.',
    bond: 'Residential contractors: $15,000 bond required.',
    lienLaw: 'Mechanics lien must be filed within 120 days of last furnishing. Pre-lien notice required within 45 days.',
    workerClassification: 'Minnesota uses economic reality test — stricter than federal.',
    prevailingWage: 'Minnesota has state prevailing wage for public projects over $25,000.',
    osha: 'Minnesota has a state OSHA plan (MNOSHA).',
    continuingEducation: 'Residential contractors: continuing education required for renewal.',
  },
  Illinois: {
    licensing: 'No state general contractor license. Roofing contractors must register. Chicago requires city license.',
    bond: 'Varies by municipality.',
    lienLaw: 'File mechanics lien within 4 months of last work. Subcontractors: 90-day notice to owner required.',
    workerClassification: 'Illinois uses ABC test (Employee Classification Act) — very strict.',
    prevailingWage: 'State prevailing wage law — Illinois Prevailing Wage Act.',
    osha: 'Federal OSHA applies — no state plan.',
    continuingEducation: 'N/A for general contractors.',
  },
  Texas: {
    licensing: 'No state general contractor license. TDLR licenses specific trades (electrical, plumbing, HVAC).',
    bond: 'Varies by trade and local jurisdiction.',
    lienLaw: 'File mechanics lien affidavit by the 15th day of 4th month after work completed. Residential: preliminary notice within 30 days.',
    workerClassification: 'Texas follows IRS guidelines. No state ABC test.',
    prevailingWage: 'No state prevailing wage law.',
    osha: 'Federal OSHA applies.',
    continuingEducation: 'Trade-specific CE required for licensed trades (electrical, plumbing, HVAC).',
  },
  California: {
    licensing: 'CSLB license required for projects >$500. Class A (General Engineering), B (General Building), C (Specialty).',
    bond: '$25,000 contractor bond required.',
    lienLaw: 'Preliminary notice within 20 days. Mechanics lien within 90 days of completion (60 days for owner-occupied residential).',
    workerClassification: 'California uses strict ABC test (Dynamex/AB5) — very aggressive classification.',
    prevailingWage: 'State prevailing wage for public works projects, enforced by DIR.',
    osha: 'Cal/OSHA state plan with stricter standards than federal.',
    continuingEducation: 'No mandatory CE but license renewal every 2 years.',
  },
  Florida: {
    licensing: 'State certified or county registered. CGC (General Contractor), CBC (Building Contractor), or specialty.',
    bond: 'Varies. Financial statement or bond required for certification.',
    lienLaw: 'File notice to owner within 45 days of first furnishing. Claim of lien within 90 days of last work.',
    workerClassification: 'Florida follows IRS guidelines. Construction industry has specific statutory test under FL §440.02.',
    prevailingWage: 'No state prevailing wage law.',
    osha: 'Federal OSHA applies.',
    continuingEducation: '14 hours CE per 2-year renewal cycle (1 hr workplace safety, 1 hr business practices).',
  },
  'North Carolina': {
    licensing: 'General contractor license required for projects >$30,000. Licensed by NC Licensing Board.',
    bond: 'No bond required for state license.',
    lienLaw: 'File claim of lien within 120 days of last furnishing. Subcontractors: notice to lien agent required within 15 days of first furnishing.',
    workerClassification: 'Follows IRS guidelines and common law test.',
    prevailingWage: 'No state prevailing wage law.',
    osha: 'NC has a state OSHA plan (NC OSHR).',
    continuingEducation: 'No mandatory CE for general contractors.',
  },
  Maryland: {
    licensing: 'Home Improvement Contractor license required for residential work. Commercial: local licenses vary.',
    bond: 'HIC: $20,000 bond required.',
    lienLaw: 'File mechanics lien within 180 days of last work. Preliminary notice required before filing.',
    workerClassification: 'Maryland follows common law test.',
    prevailingWage: 'State prevailing wage for public works projects over $500K.',
    osha: 'Maryland has a state OSHA plan.',
    continuingEducation: 'HIC: continuing education required for renewal.',
  },
  'New York': {
    licensing: 'No state general contractor license. NYC requires DOB license. Other municipalities vary.',
    bond: 'Varies by municipality.',
    lienLaw: "File mechanics lien within 8 months of last work (4 months for residential in NYC). Must serve within 30 days of filing.",
    workerClassification: 'New York uses common law and ABC test for unemployment/workers comp.',
    prevailingWage: 'State prevailing wage for public works, enforced by DOL.',
    osha: 'Federal OSHA applies. NYC has additional requirements.',
    continuingEducation: 'NYC license holders: continuing education required.',
  },
  'South Carolina': {
    licensing: 'General contractor license required for projects >$5,000. Licensed by SC LLR. Specialty trades separately licensed.',
    bond: 'Group 4+ contractors: $15,000 surety bond required.',
    lienLaw: 'File mechanics lien within 90 days of last furnishing. Preliminary notice required within 30 days of first furnishing.',
    workerClassification: 'South Carolina follows IRS 20-factor test.',
    prevailingWage: 'No state prevailing wage law. Davis-Bacon applies to federal projects.',
    osha: 'South Carolina has a state OSHA plan (SC OSHA under LLR).',
    continuingEducation: 'No mandatory CE for general contractors.',
  },
  Pennsylvania: {
    licensing: 'No state general contractor license required. Home Improvement Contractor registration required for residential work >$500.',
    bond: 'Home Improvement Contractor: $50,000 bond or insurance required.',
    lienLaw: 'File mechanics lien within 6 months of last work. Preliminary notice (Notice of Furnishing) required within first 30 days.',
    workerClassification: 'Pennsylvania Construction Workplace Misclassification Act — strict penalties for misclassification.',
    prevailingWage: 'Pennsylvania Prevailing Wage Act for public projects >$25,000.',
    osha: 'Federal OSHA applies — no state plan.',
    continuingEducation: 'No mandatory CE for general contractors.',
  },
  Ohio: {
    licensing: 'No state general contractor license. Specialty trades (electrical, plumbing, HVAC) require state license. Some cities require local licenses.',
    bond: 'Varies by trade and local jurisdiction.',
    lienLaw: 'File mechanics lien within 60 days of last work for residential; 75 days for commercial. Subcontractors: 21-day notice requirement.',
    workerClassification: 'Ohio follows IRS guidelines and common law test.',
    prevailingWage: 'Ohio Prevailing Wage Law for public projects; repealed for local projects in 2017 but applies to state projects.',
    osha: 'Federal OSHA applies — no state plan.',
    continuingEducation: 'Trade-specific CE for licensed specialty contractors.',
  },
  Alabama: {
    licensing: 'General contractor license required for commercial projects >$50,000. Home builder license for residential >$10,000 (HBLB).',
    bond: 'No statewide GC bond; some municipalities require local bonds.',
    lienLaw: 'Original contractors file verified lien statement within 6 months of last work. Material suppliers: 4 months. Notice to owner required for non-original contractors.',
    workerClassification: 'Follows IRS common-law / 20-factor guidelines. No state ABC test.',
    prevailingWage: 'No state prevailing wage law. Davis-Bacon applies to federal projects.',
    osha: 'Federal OSHA applies — no state plan.',
    continuingEducation: 'Home builders: CE required for renewal. Commercial GC: none.',
  },
  Alaska: {
    licensing: 'General contractor license required (with or without residential endorsement). Residential endorsement requires cold-climate course.',
    bond: 'General contractor: $25,000 surety bond. Specialty: $10,000. Handyman: $5,000.',
    lienLaw: 'Claim of lien within 90 days of last furnishing (120 days if a notice of completion is not recorded). Notice of right to lien preserves priority.',
    workerClassification: 'Alaska uses an ABC test for unemployment insurance coverage.',
    prevailingWage: 'Little Davis-Bacon Act — state prevailing wage on public construction >$25,000.',
    osha: 'Alaska has a state OSHA plan (AKOSH).',
    continuingEducation: '16 hours CE per 2-year renewal for residential-endorsed contractors.',
  },
  Arizona: {
    licensing: 'ROC contractor license required for most work over $1,000 (handyman exemption below). Separate commercial/residential classifications.',
    bond: 'License bond required — amount varies by classification and volume ($1,000–$100,000).',
    lienLaw: '20-day preliminary notice required. File lien within 120 days of completion (60 days if notice of completion recorded). Owner-occupied residential largely lien-exempt.',
    workerClassification: 'Follows IRS guidelines; declaration of independent business status available under state law.',
    prevailingWage: 'No state prevailing wage law (state statute prohibits local prevailing wage on state-funded work).',
    osha: 'Arizona has a state OSHA plan (ADOSH).',
    continuingEducation: 'No mandatory CE for license renewal.',
  },
  Arkansas: {
    licensing: 'Contractor license required for commercial projects ≥$50,000. Residential builder license for projects >$2,000.',
    bond: '$10,000 bond commonly required with licensing for some classifications.',
    lienLaw: 'File lien within 120 days of last furnishing. Residential: pre-construction notice required before work; subs/suppliers give 75-day notice.',
    workerClassification: 'Follows IRS common-law guidelines. No state ABC test for wage law.',
    prevailingWage: 'State prevailing wage repealed in 2017. Davis-Bacon applies to federal projects.',
    osha: 'Federal OSHA applies — no state plan.',
    continuingEducation: 'Residential builders: CE hours required for renewal.',
  },
  Colorado: {
    licensing: 'No state general contractor license — licensing is municipal/county. Electricians and plumbers licensed at state level.',
    bond: 'Varies by local jurisdiction.',
    lienLaw: 'File lien within 4 months of last work (2 months for labor-only). Serve Notice of Intent to file at least 10 days before recording.',
    workerClassification: 'Colorado uses a strict two-part test (free from control + independent business) under CESA.',
    prevailingWage: 'State prevailing wage on state agency projects ≥$500,000 (2019 law). Davis-Bacon on federal work.',
    osha: 'Federal OSHA applies — no state plan.',
    continuingEducation: 'Trade-specific CE for state-licensed trades; GC per local rules.',
  },
  Connecticut: {
    licensing: 'No state GC exam license. Home Improvement Contractor and New Home Construction Contractor registration required for residential. Major Contractor registration for large commercial.',
    bond: 'No statewide bond; Home Improvement Guaranty Fund funded by registration fees.',
    lienLaw: 'File mechanics lien within 90 days of ceasing work; serve owner within 30 days of recording.',
    workerClassification: 'Connecticut uses the ABC test for unemployment purposes — strict.',
    prevailingWage: 'State prevailing wage: new construction ≥$1,000,000; renovation ≥$100,000.',
    osha: 'Federal OSHA for private sector; CONN-OSHA covers public sector.',
    continuingEducation: 'None for HIC registration; trades have CE requirements.',
  },
  Delaware: {
    licensing: 'Contractor business license from Division of Revenue required; no exam-based state GC license. Non-resident contractors post additional requirements.',
    bond: 'Non-resident contractors: surety bond required on contracts ≥$20,000.',
    lienLaw: 'Statement of claim filed in Superior Court — generally within 180 days after completion of the structure (subcontractors: 120 days from last work).',
    workerClassification: 'Delaware Workplace Fraud Act applies ABC test to construction — strict penalties.',
    prevailingWage: 'State prevailing wage: new construction ≥$500,000; alteration/repair ≥$45,000.',
    osha: 'Federal OSHA applies — no state plan.',
    continuingEducation: 'N/A — no exam-based state GC license.',
  },
  'District of Columbia': {
    licensing: 'Basic Business License required; Home Improvement Contractor endorsement for residential work. General contractor/construction manager license category applies.',
    bond: 'Home improvement contractors: $25,000 surety bond (or approved alternative).',
    lienLaw: 'Record notice of mechanics lien within 90 days after completion or termination of the project; enforce within 180 days.',
    workerClassification: 'DC Workplace Fraud Act applies ABC test to construction services.',
    prevailingWage: 'Davis-Bacon rates apply to DC government construction contracts.',
    osha: 'Federal OSHA applies.',
    continuingEducation: 'No mandatory CE for the basic license.',
  },
  Hawaii: {
    licensing: 'Contractor license required from CLB (A General Engineering, B General Building, C Specialty). Strict enforcement — unlicensed work over $1,500 barred from lien/suit.',
    bond: 'No universal bond; financial responsibility requirements and recovery fund contributions apply.',
    lienLaw: 'Application for lien within 45 days after completion — one of the shortest windows in the U.S. Court hearing required before lien attaches.',
    workerClassification: 'ABC test for unemployment coverage.',
    prevailingWage: 'Chapter 104 state prevailing wage on public works >$2,000.',
    osha: 'Hawaii has a state OSHA plan (HIOSH).',
    continuingEducation: 'No mandatory CE; biennial renewal.',
  },
  Idaho: {
    licensing: 'Contractor registration (not exam-based) required with Idaho Contractors Board. Public works contractors need a public works license.',
    bond: 'No general bond for registration; public works license has financial requirements.',
    lienLaw: 'File claim of lien within 90 days of completion or last furnishing; serve owner within 5 business days; enforce within 6 months.',
    workerClassification: 'Right-to-control test under state law; follows IRS factors.',
    prevailingWage: 'No state prevailing wage law.',
    osha: 'Federal OSHA applies — no state plan.',
    continuingEducation: 'None for registration.',
  },
  Indiana: {
    licensing: 'No state general contractor license. Plumbers licensed at state level; other trades and GCs licensed locally.',
    bond: 'Varies by municipality.',
    lienLaw: 'Sworn statement/notice of intention to lien within 90 days of last work (60 days for owner-occupied residential). Enforce within 1 year.',
    workerClassification: 'Follows IRS common-law guidelines; construction misclassification statute adds penalties.',
    prevailingWage: 'Common construction wage repealed in 2015. Davis-Bacon on federal work.',
    osha: 'Indiana has a state OSHA plan (IOSHA).',
    continuingEducation: 'Per local requirements; state plumbing CE applies.',
  },
  Iowa: {
    licensing: 'Contractor registration with Iowa Division of Labor required if doing ≥$2,000 of work per year. No exam-based GC license.',
    bond: 'Out-of-state contractors: $25,000 bond required.',
    lienLaw: 'Post lien via Mechanics Notice and Lien Registry (MNLR) within 90 days of last furnishing for full priority; residential requires early MNLR notices.',
    workerClassification: 'Follows IRS common-law guidelines.',
    prevailingWage: 'No state prevailing wage law.',
    osha: 'Iowa has a state OSHA plan (Iowa OSHA).',
    continuingEducation: 'None for registration.',
  },
  Kansas: {
    licensing: 'No state general contractor license — county/municipal licensing (e.g., Johnson County, Wichita). Trades licensed locally.',
    bond: 'Varies by local jurisdiction.',
    lienLaw: 'File lien statement within 4 months of last furnishing (subcontractors: 3 months). Residential subs must serve warning statement.',
    workerClassification: 'Follows IRS 20-factor guidelines.',
    prevailingWage: 'No state prevailing wage law.',
    osha: 'Federal OSHA applies — no state plan.',
    continuingEducation: 'Per local licensing rules.',
  },
  Kentucky: {
    licensing: 'No state general contractor license. Electrical, plumbing, HVAC licensed at state level; some cities license GCs.',
    bond: 'Varies by local jurisdiction.',
    lienLaw: 'File lien statement within 6 months of last work; owner-occupied residential requires written notice within 75 days. Enforce within 1 year.',
    workerClassification: 'Follows IRS common-law guidelines.',
    prevailingWage: 'State prevailing wage repealed in 2017. Davis-Bacon on federal work.',
    osha: 'Kentucky has a state OSHA plan (KY OSH).',
    continuingEducation: 'Trade-specific CE for state-licensed trades.',
  },
  Louisiana: {
    licensing: 'State contractor license required: commercial ≥$50,000; residential ≥$75,000; home improvement registration $7,500–$75,000. Licensed by LSLBC.',
    bond: 'No universal bond; financial statement requirements apply.',
    lienLaw: 'Private Works Act: file statement of claim within 60 days after notice of termination or substantial completion (subs on residential without notice of contract: 70 days).',
    workerClassification: 'Follows IRS guidelines; state misclassification penalties apply.',
    prevailingWage: 'No state prevailing wage law.',
    osha: 'Federal OSHA applies — no state plan.',
    continuingEducation: 'CE required for some classifications (e.g., residential: 6 hours/year).',
  },
  Maine: {
    licensing: 'No state general contractor license. Electricians and plumbers state-licensed. Home construction contracts >$3,000 require written contract with statutory terms.',
    bond: 'None statewide.',
    lienLaw: 'File lien within 90 days of last furnishing; enforce within 120 days of last furnishing.',
    workerClassification: 'Maine uses a strict multi-factor independent contractor test.',
    prevailingWage: 'State prevailing wage on public construction ≥$50,000.',
    osha: 'Federal OSHA for private sector; state plan covers public employees only.',
    continuingEducation: 'Trade-specific CE for licensed trades.',
  },
  Massachusetts: {
    licensing: 'Construction Supervisor License (CSL) for structural work on 1–4 family dwellings; Home Improvement Contractor (HIC) registration for residential remodeling. No commercial GC license.',
    bond: 'HIC: Guaranty Fund contribution in lieu of bond.',
    lienLaw: 'Record notice of contract by the earlier of 90 days after last furnishing; statement of account within 120 days. Strict statutory sequence.',
    workerClassification: 'Massachusetts ABC test — one of the strictest in the nation (wage law).',
    prevailingWage: 'State prevailing wage on all public construction, enforced by AGO/DLS.',
    osha: 'Federal OSHA applies — no state plan for private sector.',
    continuingEducation: 'CSL: 12 hours CE per 2-year cycle.',
  },
  Michigan: {
    licensing: 'Residential builder or maintenance & alteration license required for residential work >$600. Commercial: no state GC license.',
    bond: 'None for residential builder license.',
    lienLaw: 'Notice of commencement system; subs/suppliers serve notice of furnishing within 20 days. Record claim of lien within 90 days of last furnishing; enforce within 1 year.',
    workerClassification: 'Follows IRS 20-factor test (adopted by statute for some purposes).',
    prevailingWage: 'Prevailing wage repealed 2018, reinstated March 2024 for state projects.',
    osha: 'Michigan has a state OSHA plan (MIOSHA).',
    continuingEducation: 'Residential builders: 21 hours CE in first renewal cycle, then 3 hrs/yr (waived after 6 years).',
  },
  Mississippi: {
    licensing: 'Certificate of responsibility required: commercial >$50,000; residential builder >$50,000; residential remodeler >$10,000 (MSBOC).',
    bond: 'None statewide; project bonds per contract.',
    lienLaw: 'Construction lien law (2014): file claim of lien within 90 days of last work; subs/suppliers must have given pre-lien notice. Enforce within 180 days.',
    workerClassification: 'Follows IRS common-law guidelines.',
    prevailingWage: 'No state prevailing wage law.',
    osha: 'Federal OSHA applies — no state plan.',
    continuingEducation: 'None statewide for GC.',
  },
  Missouri: {
    licensing: 'No state general contractor license — licensing at city/county level (KC, St. Louis). Trades licensed locally.',
    bond: 'Varies by local jurisdiction.',
    lienLaw: 'File lien within 6 months of last work. Original contractors on residential must give consent-of-owner notice; subs give 10-day notice of intent.',
    workerClassification: 'Follows IRS 20-factor guidelines.',
    prevailingWage: 'State prevailing wage on public works >$75,000 (Annual Wage Order).',
    osha: 'Federal OSHA applies — no state plan.',
    continuingEducation: 'Per local licensing rules.',
  },
  Montana: {
    licensing: 'Construction contractor registration required for contractors with employees (no exam). Independent contractor exemption certificate available.',
    bond: 'None for registration.',
    lienLaw: 'File construction lien within 90 days of last furnishing; subs/suppliers file notice of right to claim lien within 20 days of first furnishing (residential).',
    workerClassification: 'Independent Contractor Central Unit (ICCU) certification system — strict.',
    prevailingWage: 'State prevailing wage on public works contracts >$25,000.',
    osha: 'Federal OSHA applies — no state plan for private sector.',
    continuingEducation: 'None for registration.',
  },
  Nebraska: {
    licensing: 'Contractor registration with Nebraska DOL required (≥$2,500 jobs). No exam-based state GC license; Omaha/Lincoln license locally.',
    bond: 'None for registration; non-resident contractors post surety for tax.',
    lienLaw: 'Record lien within 120 days of last furnishing; enforce within 2 years. Residential protected-party rules limit lien to unpaid contract price.',
    workerClassification: 'Nebraska Employee Classification Act — ABC-style test for construction.',
    prevailingWage: 'No state prevailing wage law.',
    osha: 'Federal OSHA applies — no state plan.',
    continuingEducation: 'None for registration.',
  },
  Nevada: {
    licensing: 'State contractor license required for all work ≥$1,000 (NSCB). Strict enforcement — unlicensed contracting is criminal.',
    bond: 'License bond required — $1,000 to $500,000 set by board based on volume/class.',
    lienLaw: 'Record notice of lien within 90 days after completion or last furnishing. Subs/suppliers: notice of right to lien required. Residential pre-lien notice rules apply.',
    workerClassification: 'Conclusive presumption of IC status if statutory criteria met; otherwise economic-reality style analysis.',
    prevailingWage: 'State prevailing wage on public works ≥$250,000.',
    osha: 'Nevada has a state OSHA plan (Nevada OSHA).',
    continuingEducation: 'None statewide; board may impose per license.',
  },
  'New Hampshire': {
    licensing: 'No state general contractor license. Electricians and plumbers state-licensed.',
    bond: 'None statewide.',
    lienLaw: 'Mechanics lien secured by court attachment within 120 days of last furnishing. Subs/suppliers should give notice to preserve rights.',
    workerClassification: 'Multi-part statutory test (7 criteria) for IC status — strict.',
    prevailingWage: 'No state prevailing wage law.',
    osha: 'Federal OSHA applies — no state plan.',
    continuingEducation: 'Trade-specific CE for licensed trades.',
  },
  'New Jersey': {
    licensing: 'Home Improvement Contractor registration (DCA) required for residential remodeling; new home builders register separately. No commercial GC license.',
    bond: 'None for HIC registration; insurance required ($500K CGL).',
    lienLaw: 'Non-residential: file lien within 90 days of last work. Residential: Notice of Unpaid Balance + arbitration within 60 days, lien within 120 days — strict two-step process.',
    workerClassification: 'New Jersey ABC test — strictly enforced with misclassification penalties.',
    prevailingWage: 'State prevailing wage on public work ≥$16,263 (municipal) / lower thresholds otherwise; updated periodically.',
    osha: 'Federal OSHA for private sector; PEOSH covers public employees.',
    continuingEducation: 'None for HIC registration.',
  },
  'New Mexico': {
    licensing: 'State contractor license required (CID/RLD) — GB98 general building and specialty classifications. Unlicensed work barred from payment suit.',
    bond: '$10,000 code-compliance bond may be required in certain cases.',
    lienLaw: 'File lien within 120 days of completion (original contractor); subs/suppliers 90 days. Residential ≤4 units: pre-lien notice required for subs/suppliers.',
    workerClassification: 'ABC test for unemployment purposes.',
    prevailingWage: 'State prevailing wage (Public Works Minimum Wage Act) on public projects >$60,000.',
    osha: 'New Mexico has a state OSHA plan (NM OSHA).',
    continuingEducation: 'Qualifying party CE required per classification cycle.',
  },
  'North Dakota': {
    licensing: 'State contractor license required for jobs ≥$4,000 (Class A–D by contract size).',
    bond: 'None for license; ND Secretary of State registration.',
    lienLaw: 'Record lien within 90 days of last furnishing (later filing loses priority against intervening interests). 10-day notice of intent before recording.',
    workerClassification: 'Common-law right-to-control test; ICs may seek advisory determination.',
    prevailingWage: 'No state prevailing wage law.',
    osha: 'Federal OSHA applies — no state plan.',
    continuingEducation: 'None.',
  },
  Oklahoma: {
    licensing: 'No state general contractor license. Electrical, mechanical, plumbing licensed by CIB. Roofing contractors must register.',
    bond: 'Trade-specific; none for GC.',
    lienLaw: 'Original contractors: file lien within 4 months of last furnishing. Subs/suppliers: 90 days + pre-lien notice for claims >$10,000 (non-residential exemptions).',
    workerClassification: 'Follows IRS 20-factor guidelines.',
    prevailingWage: 'State prevailing wage act held unconstitutional — not enforced. Davis-Bacon on federal work.',
    osha: 'Federal OSHA applies — no state plan for private sector.',
    continuingEducation: 'Trade-specific CE for CIB-licensed trades.',
  },
  Oregon: {
    licensing: 'CCB license required for all construction work. Residential and commercial endorsements; RMI exam + pre-license training.',
    bond: 'Surety bond required — $10,000–$80,000 depending on endorsement.',
    lienLaw: 'Record lien within 75 days after last furnishing or completion (whichever first). Subs/suppliers: notice of right to lien (8 days, residential). Enforce within 120 days.',
    workerClassification: 'Multi-factor independent contractor standard (ORS 670.600) — requires independently established business.',
    prevailingWage: 'State prevailing wage (BOLI) on public works ≥$50,000.',
    osha: 'Oregon has a state OSHA plan (Oregon OSHA) with stricter standards.',
    continuingEducation: 'Residential CCB: 8 hours CE per 2-year renewal (16 first cycle).',
  },
  'Rhode Island': {
    licensing: 'Contractor registration required for residential and commercial building work (CRLB). Underground utility contractors licensed.',
    bond: 'None for registration; insurance required.',
    lienLaw: 'Record notice of intention to claim lien within 200 days of doing work; complaint to enforce within 40 days after that filing window.',
    workerClassification: 'ABC test for unemployment; misclassification task force active.',
    prevailingWage: 'State prevailing wage on public works >$1,000.',
    osha: 'Federal OSHA applies — no state plan.',
    continuingEducation: '5 hours CE per registration cycle for residential contractors.',
  },
  'South Dakota': {
    licensing: 'No state general contractor license — excise tax license required for contractors. Trades and locals vary.',
    bond: 'None statewide.',
    lienLaw: 'File lien statement within 120 days of last furnishing. Owner may demand suit within 30 days after written demand.',
    workerClassification: 'Common-law right-to-control test.',
    prevailingWage: 'No state prevailing wage law.',
    osha: 'Federal OSHA applies — no state plan.',
    continuingEducation: 'None.',
  },
  Tennessee: {
    licensing: 'State contractor license required for projects ≥$25,000 (Board for Licensing Contractors). Home improvement license for $3,000–$24,999 in some counties.',
    bond: 'Home improvement license: $10,000 bond. GC: financial statement sets monetary limit.',
    lienLaw: 'Record lien within 90 days of completion for priority against subsequent purchasers; subs serve notice of nonpayment monthly + 90-day notice of lien. Residential single-family: lien limited to prime contractors.',
    workerClassification: 'Follows IRS 20-factor guidelines.',
    prevailingWage: 'State prevailing wage on highway construction only; building construction repealed.',
    osha: 'Tennessee has a state OSHA plan (TOSHA).',
    continuingEducation: 'None for GC license (renewal every 2 years).',
  },
  Utah: {
    licensing: 'DOPL contractor license required (general building, general engineering, specialty). Pre-license course + exams.',
    bond: 'No universal bond; Residence Lien Recovery Fund participation.',
    lienLaw: 'Preconstruction and construction notices filed via State Construction Registry within 20 days of starting work. Notice of construction lien within 180 days of completion; enforce within 180 days.',
    workerClassification: 'Follows IRS guidelines; construction ICs must hold own license.',
    prevailingWage: 'No state prevailing wage law.',
    osha: 'Utah has a state OSHA plan (UOSH).',
    continuingEducation: '6 hours CE per 2-year renewal (3 core + 3 professional).',
  },
  Vermont: {
    licensing: 'Residential contractor registration required for projects ≥$10,000 (2023 law). Electricians/plumbers state-licensed. No commercial GC license.',
    bond: 'None for registration; insurance required.',
    lienLaw: 'Record memorandum of lien within 180 days of when payment became due for the last work; enforce (attachment) within 180 days of recording.',
    workerClassification: 'ABC test for unemployment purposes.',
    prevailingWage: 'State projects use mean wage rates (VT prevailing wage) on state construction >$100,000.',
    osha: 'Vermont has a state OSHA plan (VOSHA).',
    continuingEducation: 'None yet for registration.',
  },
  Washington: {
    licensing: 'Contractor registration with L&I required (general or specialty). Exam not required; insurance mandatory.',
    bond: 'General: $30,000 bond; specialty: $15,000 (amounts per current L&I schedule).',
    lienLaw: 'Record claim of lien within 90 days of last furnishing. Suppliers/professional services/subs give pre-claim notice to owner (60/10-day rules). Enforce within 8 months.',
    workerClassification: 'Multi-part statutory test (6/7-part) for construction — strict.',
    prevailingWage: 'State prevailing wage on all public works, enforced by L&I.',
    osha: 'Washington has a state OSHA plan (DOSH/WISHA) with stricter standards.',
    continuingEducation: 'None for registration (training required for some specialty trades).',
  },
  'West Virginia': {
    licensing: 'State contractor license required for projects ≥$5,000 ($10,000 electrical/plumbing/HVAC). WV Contractor Licensing Board.',
    bond: 'Wage bond may be required for new construction employers (waivable after 5 years).',
    lienLaw: 'Record lien within 100 days of last furnishing (all tiers); serve owner within same window. Enforce within 6 months.',
    workerClassification: 'West Virginia Employment Law Worker Classification Act — ABC-style standards.',
    prevailingWage: 'State prevailing wage repealed in 2016. Davis-Bacon on federal work.',
    osha: 'Federal OSHA applies — no state plan.',
    continuingEducation: 'None for GC license renewal.',
  },
  Wisconsin: {
    licensing: 'Dwelling Contractor certification (with qualifier) required for 1–2 family residential permits. No state commercial GC license.',
    bond: 'Financial responsibility (bond/insurance/net worth) for dwelling contractor certification.',
    lienLaw: 'Prime contractors on residential: 2 written notices (contract + before lien). Record claim of lien within 6 months of last work; serve copy on owner ≥30 days prior notice of intent.',
    workerClassification: '9-part statutory test for construction ICs — strict.',
    prevailingWage: 'State prevailing wage repealed (2017-18). Davis-Bacon on federal work.',
    osha: 'Federal OSHA applies — no state plan for private sector.',
    continuingEducation: 'Dwelling contractor qualifier: 12 hours CE per 2-year cycle.',
  },
  Wyoming: {
    licensing: 'No state general contractor license — municipal licensing (Cheyenne, Casper). Electricians licensed at state level.',
    bond: 'Varies by local jurisdiction.',
    lienLaw: 'Contractors: record lien within 150 days of last work (subs/suppliers: 120 days). 20-day pre-lien notice after first furnishing; 10-day notice of intent before filing.',
    workerClassification: 'Common-law right-to-control test.',
    prevailingWage: 'State prevailing wage applies to state-funded public works (verify current thresholds).',
    osha: 'Wyoming has a state OSHA plan (Wyoming OSHA).',
    continuingEducation: 'Per local licensing rules.',
  },
};

export function getStateLegal(state: string): StateLegalData | undefined {
  return STATE_LEGAL[state];
}

export const AVAILABLE_STATES = Object.keys(STATE_LEGAL).sort();
