import type { LocationData } from './types.js';

export const VIRGINIA_LOCATIONS: LocationData[] = [
  { slug: 'richmond', city: 'Richmond', county: 'City of Richmond', state: 'Virginia', stateAbbr: 'VA', lat: 37.5407, lng: -77.4360, population: 226610, metaTitle: 'Asphalt Paving Richmond VA | J. Worden & Sons | (804) 446-1296', metaDescription: 'J. Worden & Sons — 4th-generation asphalt paving contractors serving Richmond, VA. Driveways, parking lots, commercial paving. Free estimates.', h1: 'Asphalt Paving in Richmond, VA' },
  { slug: 'chesterfield', city: 'Chesterfield', county: 'Chesterfield County', state: 'Virginia', stateAbbr: 'VA', lat: 37.3765, lng: -77.5352, population: 367766, metaTitle: 'Asphalt Paving Chesterfield VA | J. Worden & Sons', metaDescription: 'Trusted asphalt paving contractor in Chesterfield County, VA. Residential driveways, commercial parking lots, sealcoating. Call (804) 446-1296.', h1: 'Asphalt Paving in Chesterfield County, VA' },
  { slug: 'henrico', city: 'Henrico', county: 'Henrico County', state: 'Virginia', stateAbbr: 'VA', lat: 37.5499, lng: -77.3459, population: 334389, metaTitle: 'Asphalt Paving Henrico VA | J. Worden & Sons', metaDescription: 'Professional asphalt paving in Henrico County, VA. 4th-generation quality since 1984. Free estimates — call (804) 446-1296.', h1: 'Asphalt Paving in Henrico County, VA' },
  { slug: 'mechanicsville', city: 'Mechanicsville', county: 'Hanover County', state: 'Virginia', stateAbbr: 'VA', lat: 37.6087, lng: -77.3736, population: 36348, metaTitle: 'Asphalt Paving Mechanicsville VA | J. Worden & Sons', metaDescription: 'Asphalt driveways, parking lots, and sealcoating in Mechanicsville, VA. Local, trusted, 4th-generation. Call (804) 446-1296.', h1: 'Asphalt Paving in Mechanicsville, VA' },
  { slug: 'midlothian', city: 'Midlothian', county: 'Chesterfield County', state: 'Virginia', stateAbbr: 'VA', lat: 37.4935, lng: -77.6441, population: 65985, metaTitle: 'Asphalt Paving Midlothian VA | J. Worden & Sons', metaDescription: 'J. Worden & Sons serves Midlothian, VA with expert asphalt paving, sealcoating, and commercial paving. Free estimates.', h1: 'Asphalt Paving in Midlothian, VA' },
  { slug: 'glen-allen', city: 'Glen Allen', county: 'Henrico County', state: 'Virginia', stateAbbr: 'VA', lat: 37.6626, lng: -77.4958, population: 19113, metaTitle: 'Asphalt Paving Glen Allen VA | J. Worden & Sons', metaDescription: 'Top-rated asphalt paving contractors in Glen Allen, VA. Residential, commercial, industrial. Call (804) 446-1296.', h1: 'Asphalt Paving in Glen Allen, VA' },
  { slug: 'chester', city: 'Chester', county: 'Chesterfield County', state: 'Virginia', stateAbbr: 'VA', lat: 37.3565, lng: -77.4427, population: 21200, metaTitle: 'Asphalt Paving Chester VA | J. Worden & Sons', metaDescription: 'Expert asphalt paving in Chester, VA. Driveways, parking lots, crack repair. J. Worden & Sons — (804) 446-1296.', h1: 'Asphalt Paving in Chester, VA' },
  { slug: 'ashland', city: 'Ashland', county: 'Hanover County', state: 'Virginia', stateAbbr: 'VA', lat: 37.7598, lng: -77.4797, population: 8108, metaTitle: 'Asphalt Paving Ashland VA | J. Worden & Sons', metaDescription: 'Asphalt paving services in Ashland, VA and Hanover County. Quality driveways, parking lots, and chip seal. Call (804) 446-1296.', h1: 'Asphalt Paving in Ashland, VA' },
  { slug: 'colonial-heights', city: 'Colonial Heights', county: 'City of Colonial Heights', state: 'Virginia', stateAbbr: 'VA', lat: 37.2598, lng: -77.4016, population: 18720, metaTitle: 'Asphalt Paving Colonial Heights VA | J. Worden & Sons', metaDescription: 'Asphalt paving contractor in Colonial Heights, VA. Commercial and residential services. Call (804) 446-1296.', h1: 'Asphalt Paving in Colonial Heights, VA' },
  { slug: 'hopewell', city: 'Hopewell', county: 'City of Hopewell', state: 'Virginia', stateAbbr: 'VA', lat: 37.3043, lng: -77.2877, population: 23900, metaTitle: 'Asphalt Paving Hopewell VA | J. Worden & Sons', metaDescription: 'J. Worden & Sons serves Hopewell, VA with quality asphalt paving and sealcoating. Free estimates — (804) 446-1296.', h1: 'Asphalt Paving in Hopewell, VA' },
  { slug: 'petersburg', city: 'Petersburg', county: 'City of Petersburg', state: 'Virginia', stateAbbr: 'VA', lat: 37.2279, lng: -77.4019, population: 33000, metaTitle: 'Asphalt Paving Petersburg VA | J. Worden & Sons', metaDescription: 'Professional asphalt paving in Petersburg, VA. Residential, commercial, municipal. J. Worden & Sons.', h1: 'Asphalt Paving in Petersburg, VA' },
  { slug: 'hanover', city: 'Hanover', county: 'Hanover County', state: 'Virginia', stateAbbr: 'VA', lat: 37.7551, lng: -77.3736, population: 107000, metaTitle: 'Asphalt Paving Hanover County VA | J. Worden & Sons', metaDescription: 'Trusted asphalt paving in Hanover County, VA. Driveways, parking lots, commercial. Call (804) 446-1296.', h1: 'Asphalt Paving in Hanover County, VA' },
  { slug: 'goochland', city: 'Goochland', county: 'Goochland County', state: 'Virginia', stateAbbr: 'VA', lat: 37.6762, lng: -77.8969, population: 24000, metaTitle: 'Asphalt Paving Goochland VA | J. Worden & Sons', metaDescription: 'Asphalt paving services in Goochland County, VA. Quality work, fair pricing. Call (804) 446-1296.', h1: 'Asphalt Paving in Goochland County, VA' },
  { slug: 'powhatan', city: 'Powhatan', county: 'Powhatan County', state: 'Virginia', stateAbbr: 'VA', lat: 37.5529, lng: -77.9152, population: 30000, metaTitle: 'Asphalt Paving Powhatan VA | J. Worden & Sons', metaDescription: 'J. Worden & Sons serves Powhatan County with expert asphalt and paving services. Free estimates.', h1: 'Asphalt Paving in Powhatan County, VA' },
  { slug: 'short-pump', city: 'Short Pump', county: 'Henrico County', state: 'Virginia', stateAbbr: 'VA', lat: 37.6516, lng: -77.6135, population: 24000, metaTitle: 'Asphalt Paving Short Pump VA | J. Worden & Sons', metaDescription: 'Asphalt paving and sealcoating in Short Pump, VA. Commercial, residential, industrial. Call (804) 446-1296.', h1: 'Asphalt Paving in Short Pump, VA' },
  { slug: 'bon-air', city: 'Bon Air', county: 'Chesterfield County', state: 'Virginia', stateAbbr: 'VA', lat: 37.5079, lng: -77.5724, population: 16000, metaTitle: 'Asphalt Paving Bon Air VA | J. Worden & Sons', metaDescription: 'Expert asphalt paving in Bon Air, VA. Driveways, parking lots, crack repair.', h1: 'Asphalt Paving in Bon Air, VA' },
  { slug: 'sandston', city: 'Sandston', county: 'Henrico County', state: 'Virginia', stateAbbr: 'VA', lat: 37.5240, lng: -77.3128, population: 8200, metaTitle: 'Asphalt Paving Sandston VA | J. Worden & Sons', metaDescription: 'Asphalt paving contractor in Sandston and East Henrico, VA.', h1: 'Asphalt Paving in Sandston, VA' },
  { slug: 'fredericksburg', city: 'Fredericksburg', county: 'City of Fredericksburg', state: 'Virginia', stateAbbr: 'VA', lat: 38.3032, lng: -77.4605, population: 29000, metaTitle: 'Asphalt Paving Fredericksburg VA | J. Worden & Sons', metaDescription: 'Professional asphalt paving in Fredericksburg, VA. Commercial and residential paving services. Call (804) 446-1296.', h1: 'Asphalt Paving in Fredericksburg, VA' },
  { slug: 'charlottesville', city: 'Charlottesville', county: 'City of Charlottesville', state: 'Virginia', stateAbbr: 'VA', lat: 38.0293, lng: -78.4767, population: 46500, metaTitle: 'Asphalt Paving Charlottesville VA | J. Worden & Sons', metaDescription: 'J. Worden & Sons serves Charlottesville, VA with expert asphalt paving and general contracting services.', h1: 'Asphalt Paving in Charlottesville, VA' },
  { slug: 'virginia-beach', city: 'Virginia Beach', county: 'City of Virginia Beach', state: 'Virginia', stateAbbr: 'VA', lat: 36.8529, lng: -75.9780, population: 459000, metaTitle: 'Asphalt Paving Virginia Beach VA | J. Worden & Sons', metaDescription: 'Asphalt paving contractor serving Virginia Beach, VA. Commercial, residential, and industrial paving.', h1: 'Asphalt Paving in Virginia Beach, VA' },
];

export function getLocationBySlug(slug: string): LocationData | undefined {
  return VIRGINIA_LOCATIONS.find((l) => l.slug === slug);
}
